ZMSG_NEWJOB              = 0
ZMSG_ACK                 = 1
ZMSG_FINISHED            = 2
ZMSG_FINISHED_FILES      = 3

ZMSG_RESUME_WORKER       = 4
ZMSG_PAUSE_WORKER        = 5

ZMSG_LOCAL_EXIT          = 6
ZMSG_LOCAL_RESET_JOB     = 7
ZMSG_LOCAL_RESUME_WORKER = 8
ZMSG_LOCAL_PAUSE_WORKER  = 9
